---
- hosts: test
  remote_user: ansible
  vars:
  - warName: sample-java-project.war
  - tomcat_version: 9.0.73
  - warRemotePath: /usr/local/tomcat/webapps

  tasks:
      
  - name: Copy WAR to Remote server
    become: true
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }}
